### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by straki** [jetty-project/http2-demo#1]
When I try to run with $ mvn jetty:run-forked i get this error.

[ERROR] Failed to execute goal org.mortbay.jetty:jetty-maven-plugin:8.1.16.v20140903:run-forked (default-cli) on project http2-demo: The parameters 'stopKey', 'stopPort' for goal org.mortbay.jetty:jetty-maven-plugin:8.1.16.v20140903:run-forked are missing or invalid -> [Help 1]

**Comment by joakime** [comment]
You have an old jetty-maven-plugin there.
The project is configured for org.eclipse.jetty:jetty-maven-plugin:9.3.0.v20150601:run-forked

**Comment by straki** [comment]
Thanks for info, i found that 9.3.0.v20150601 version doesn't exists in maven repository.
I change it to 9.3.0.v20150612 and now everything work.
